server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
#    username: fei
#    password: As!12300321
#    url: jdbc:mysql://47.102.204.121:3306/mytest?useUnicode=true&characterEncoding=utf-8
##    driver-class-name:  com.mysql.jdbc.Driver
#    username: root
#    password: zx12300321
#    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=utf-8
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://121.42.13.213:3306/tsdata?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: zx!12300321
  mail:
    host: smtp.163.com
    username: sf2033@163.com
    password: BBQXJUJVSWDCOOJK
    default-encoding: UTF-8
    properties:
         smtp:
           auth: true
           timeout: 25000
mail:
  fromMail:
    addr: sf2033@163.com

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.myuuutime.entity


#showSql
logging:
  level:
    com:
      example:
        mapper : debug
redis:
  #最大闲置数
  maxIdle: 30
  #最小闲置数
  minIdle: 10
  #最大连接数
  maxToal: 100
  #连接安装redis服务器的IP地址
  url: 127.0.0.1
  #redis的默认端口
  port: 6379
